class PrivacidadeModel {
  static const String titulo = 'Política de privacidade';
  static const String texto =
      'Todas as suas informações pessoais recolhidas, serão usadas para o ajudar a tornar a sua visita em nosso site a mais produtiva e agradável possível.\nA garantia da confidencialidade dos dados pessoais dos utilizadores do nosso site é importante para o app e para outros sistemas interligados ao mesmo. \nTodas as informações pessoais relativas a membros, assinantes, clientes ou visitantes que usem os nossos apps serão tratadas em concordância com a Lei da Proteção de Dados Pessoais de 26 de outubro de 1998 (Lei n.º 67/98).\nA informações pessoais recolhidas podem incluir o seu nome, e-mail e foto de perfil (inclusive para cadastro realizado com rede social), e também serão recolhidas as informações do dispositivo como localização, marca, modelo, versão do sistema operacional, status da bateria e tipo de conexão ativa.\nO uso dos nossos apps pressupõe a aceitação deste acordo de privacidade. Reservamos ao direito de alterar este acordo sem aviso prévio. Deste modo, recomendamos que consulte a nossa política de privacidade com regularidade de forma a estar sempre atualizado.';
  static const String terceirosTitulo = 'Ligações a sites/apps de terceiros';
  static const String terceirosTexto =
      'Os nossos apps possuem ligações para outros sites/apps, os quais, a nosso ver, podem conter informações / ferramentas úteis para os nossos visitantes. A nossa política de privacidade não é aplicada a sites/apps de terceiros, pelo que, caso visite outro site a partir do nosso deverá ler a politica de privacidade do mesmo.\nNão nos responsabilizamos pela política de privacidade ou conteúdo presente nos mesmos sites/apps.\nNão nos responsabilizamos pela integridade de informações fornecidas por terceiros.';

  static const String protecaoDadosTitulo = 'Proteção de dados';
  static const String protecaoDadosTexto =
      'Esta Política de Privacidade fornece uma visão geral de nossas práticas de privacidade e das escolhas que você pode fazer, bem como dos direitos que você pode exercer em relação aos Dados Pessoais, conforme definido abaixo, tratados por nós. Se você tiver alguma dúvida sobre o uso de Dados Pessoais, entre em contato com o encarregado de proteção de dados, pelo e-mail contato.baitatri@gmail.com.\n Nós nos comprometemos a cumprir as normas previstas na LGPD e a realizar o tratamento de dados pessoais em conformidade com os seguintes princípios: \n 1. Apenas para as finalidades determinadas nessa política, valendo-se da quantidade adequada de dados, pertinentes e limitados à necessidade e objetivo do tratamento;\n 2. De forma transparente, sendo garantido ao titular dos dados o livre acesso, a exatidão dos dados e a sua consulta facilitada;\n 3. De forma segura, por meio da adoção de medidas técnicas aptas a proteger os dados pessoais, prevenir e mitigar danos decorrentes de eventual acesso não autorizado, ou de situação acidental ou ilícita de violação de dados.\n 4. Nós realizaremos a gestão de dados pessoais durante o ciclo de vida destas informações; e \n 5. Em hipótese alguma haverá tratamento de dados para fins discriminatórios ilícitos ou abusivos.';
}
